### ISSUE TITLE
Semver version numbers

### ISSUE THREAD

**Issue by JorritSalverda** [estafette/estafette-ci-api#4]
In order to support [semver](http://semver.org/) or another type of custom version number depending on the build iteration a build counter is required.

Things to take into considerations
- counter per branch?
- label per branch but not for the _stable_ release branch (usually master)?

**Comment by JorritSalverda** [comment]
You can generate _semver_ version numbers with the following manifest snippet:

```yaml
version:
  semver:
    major: 2
    minor: 1
    patch: '{{auto}}'
    labelTemplate: '{{branch}}'
    releaseBranch: master
```

This leads to version number like `2.1.254-alpha` in case the branch name is _alpha_. For the master branch - because it's set as `releaseBranch` - the label is left out and the version number will look like `2.1.254`.

The patch number is auto incremented (across all branches) when using `'{{auto}}'` as `labelTemplate` value.

The values shown for `patch`, `labelTemplate` and `releaseBranch` are also the default values in case you leave them out.

The same behaviour can almost be accomplished using the _custom_ version definition, which has the following snippet:

```yaml
version:
  custom:
    labelTemplate: '2.1.{{auto}}-{{branch}}'
```

However the label is always set, whereas the _semver_ version leaves it out for the `releaseBranch`.

The following template placeholders can be used in the `patch` and `labelTemplate` properties:

- `{{auto}}`
- `{{branch}}`
- `{{revision}}`
